# Generated by Django 3.1.5 on 2021-01-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
