# Generated by Django 3.1.5 on 2021-01-23 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_auto_20210117_1010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trades',
        ),
    ]
